[View in Colaboratory](https://colab.research.google.com/github/trdelgado/AI4ALL-Regression/blob/master/CIFAR_10.ipynb)

# Load libraries and dataset

In [0]:
import numpy as np
import keras
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.optimizers import SGD
from keras.utils import print_summary, to_categorical

In [0]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

In [47]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(50000, 32, 32, 3)
(50000, 1)
(10000, 32, 32, 3)
(10000, 1)


In [48]:
print(x_test[0][0])

[[158 112  49]
 [159 111  47]
 [165 116  51]
 [166 118  53]
 [160 112  46]
 [156 109  41]
 [162 115  47]
 [159 113  45]
 [158 111  44]
 [159 113  41]
 [161 116  41]
 [160 111  52]
 [161 111  49]
 [166 117  41]
 [169 117  45]
 [170 119  44]
 [167 117  40]
 [162 113  38]
 [160 111  39]
 [160 112  43]
 [156 109  44]
 [149 107  45]
 [150 107  45]
 [148 106  43]
 [149 107  44]
 [143 101  39]
 [140  98  43]
 [141  97  41]
 [143  97  38]
 [137  95  36]
 [126  91  36]
 [116  85  33]]


In [49]:
print(y_test)

[[3]
 [8]
 [8]
 ...
 [5]
 [1]
 [7]]


# Data Preprocessing

In [0]:
num_classes = 10
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

In [51]:
print(y_train.shape)
print(y_test.shape)

(50000, 10)
(10000, 10)


In [0]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 250.0
x_test /= 250.0

In [53]:
print(x_test[0][0])

[[0.632 0.448 0.196]
 [0.636 0.444 0.188]
 [0.66  0.464 0.204]
 [0.664 0.472 0.212]
 [0.64  0.448 0.184]
 [0.624 0.436 0.164]
 [0.648 0.46  0.188]
 [0.636 0.452 0.18 ]
 [0.632 0.444 0.176]
 [0.636 0.452 0.164]
 [0.644 0.464 0.164]
 [0.64  0.444 0.208]
 [0.644 0.444 0.196]
 [0.664 0.468 0.164]
 [0.676 0.468 0.18 ]
 [0.68  0.476 0.176]
 [0.668 0.468 0.16 ]
 [0.648 0.452 0.152]
 [0.64  0.444 0.156]
 [0.64  0.448 0.172]
 [0.624 0.436 0.176]
 [0.596 0.428 0.18 ]
 [0.6   0.428 0.18 ]
 [0.592 0.424 0.172]
 [0.596 0.428 0.176]
 [0.572 0.404 0.156]
 [0.56  0.392 0.172]
 [0.564 0.388 0.164]
 [0.572 0.388 0.152]
 [0.548 0.38  0.144]
 [0.504 0.364 0.144]
 [0.464 0.34  0.132]]


# Model Building

In [54]:
net = Sequential()

# Layer One
net.add(Conv2D(64, (3,3), padding='same', input_shape = x_train.shape[1:]))
net.add(Activation('relu'))
net.add(MaxPooling2D(pool_size=(2,2)))
net.add(Dropout(0.3))

# Layer Two
net.add(Conv2D(64, (3,3), padding='same', input_shape = x_train.shape[1:]))
net.add(Activation('relu'))
net.add(MaxPooling2D(pool_size=(2,2)))
net.add(Dropout(0.3))

# Layer Three
net.add(Conv2D(32, (3,3), padding='same', input_shape = x_train.shape[1:]))
net.add(Activation('relu'))
net.add(MaxPooling2D(pool_size=(2,2)))
net.add(Dropout(0.2))

# Layer Four
net.add(Conv2D(32, (3,3), padding='same', input_shape = x_train.shape[1:]))
net.add(Activation('relu'))
net.add(MaxPooling2D(pool_size=(2,2)))
net.add(Dropout(0.2))

# Layer Five
net.add(Flatten())
net.add(Dense(64))
net.add(Activation('relu'))
net.add(Dropout(0.1))

# Layer Six
net.add(Dense(32))
net.add(Activation('relu'))
net.add(Dense(num_classes))
net.add(Activation('softmax'))
net.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_13 (Conv2D)           (None, 32, 32, 64)        1792      
_________________________________________________________________
activation_19 (Activation)   (None, 32, 32, 64)        0         
_________________________________________________________________
max_pooling2d_13 (MaxPooling (None, 16, 16, 64)        0         
_________________________________________________________________
dropout_16 (Dropout)         (None, 16, 16, 64)        0         
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 16, 16, 64)        36928     
_________________________________________________________________
activation_20 (Activation)   (None, 16, 16, 64)        0         
_________________________________________________________________
max_pooling2d_14 (MaxPooling (None, 8, 8, 64)          0         
__________

In [0]:
net.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train Model

In [56]:
batch_size = 128
epochs = 100
net.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2, shuffle=True)

Train on 40000 samples, validate on 10000 samples
Epoch 1/100
40000/40000 [==============================] - 11s 281us/step - loss: 1.9549 - acc: 0.2553 - val_loss: 1.6781 - val_acc: 0.3701
Epoch 2/100
40000/40000 [==============================] - 10s 261us/step - loss: 1.6367 - acc: 0.3882 - val_loss: 1.4663 - val_acc: 0.4668
Epoch 3/100
40000/40000 [==============================] - 10s 259us/step - loss: 1.4816 - acc: 0.4494 - val_loss: 1.3264 - val_acc: 0.5227
Epoch 4/100
40000/40000 [==============================] - 10s 260us/step - loss: 1.3772 - acc: 0.4949 - val_loss: 1.2443 - val_acc: 0.5513
Epoch 5/100
40000/40000 [==============================] - 10s 258us/step - loss: 1.2987 - acc: 0.5249 - val_loss: 1.1812 - val_acc: 0.5719
Epoch 6/100
40000/40000 [==============================] - 10s 261us/step - loss: 1.2480 - acc: 0.5450 - val_loss: 1.1299 - val_acc: 0.6002
Epoch 7/100
40000/40000 [==============================] - 10s 254us/step - loss: 1.2044 - acc: 0.5647 - val_l

# Test Model Performance

In [57]:
scores = net.evaluate(x_test, y_test, verbose=0)
print('Test Loss:', scores[0])
print('Test accuracy:', scores[1])

('Test Loss:', 0.6489376555919647)
('Test accuracy:', 0.7767)
